bv_write_combined_avg('G:/MRI/Hanuman',...
    '20101026/prtrtc/aftermotionremoved/predsforvtc__cue_r_2de__cue_l_2de__cue_r__cue_l.avg',...
    '20101028/prtrtc/aftermotionremoved/predsforvtc__cue_r_2de__cue_l_2de__cue_r__cue_l.avg',...
    '20101031/prtrtc/aftermotionremoved/predsforvtc__cue_r_2de__cue_l_2de__cue_r__cue_l.avg');



bv_write_combined_mdm('/data1/MRI/Florian',...
'20100609/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100630/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100701/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100702/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100704/prtrtc/beforemotionremoved/all_events_sorted.mdm')

bv_write_combined_avg('/data1/MRI/Florian',...
'20100609/prtrtc/aftermotionremoved/memsac4reward.avg',...
'20100630/prtrtc/aftermotionremoved/memsac4reward.avg',...
'20100701/prtrtc/aftermotionremoved/memsac4reward.avg',...
'20100702/prtrtc/aftermotionremoved/memsac4reward.avg',...
'20100704/prtrtc/aftermotionremoved/memsac4reward.avg');





%--------------------------------------------------


%lPULVcan1 inactivation Redrik

bv_write_combined_mdm('/data1/MRI/Redrik',...
'20100604/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100608/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100612/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100616/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100620/prtrtc/beforemotionremoved/all_events_sorted.mdm')


bv_write_combined_avg('\data1\MRI\Redrik',...
'20100604\prtrtc\aftermotionremoved\memsac4reward_memsac2decide.avg',...
'20100608\prtrtc\aftermotionremoved\memsac4reward_memsac2decide.avg',...
'20100612\prtrtc\aftermotionremoved\memsac4reward_memsac2decide.avg',...
'20100616\prtrtc\aftermotionremoved\memsac4reward_memsac2decide.avg',...
'20100620\prtrtc\aftermotionremoved\memsac4reward_memsac2decide.avg');


%baseline lPULVcan1 inactivation Redrik
bv_write_combined_mdm('/data1/MRI/Redrik',...
'20100606/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100610/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100614/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20100618/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data1/MRI/Redrik',...
'20100606/prtrtc/aftermotionremoved/memsac4reward_memsac2decide.avg',...
'20100610/prtrtc/aftermotionremoved/memsac4reward_memsac2decide.avg',...
'20100614/prtrtc/aftermotionremoved/memsac4reward_memsac2decide.avg',...
'20100618/prtrtc/aftermotionremoved/memsac4reward_memsac2decide.avg');


% -------------------------------------------------------------------------


%LIP inactivation Redrik
bv_write_combined_mdm('/data1/MRI/Redrik',...
'20090930/prtrtc/beforemotionremoved/all_events_sorted_1_2_3_.mdm',...
'20091006/prtrtc/beforemotionremoved/all_events_sorted_1_2_3_.mdm');
'20091215/prtrtc/beforemotionremoved/all_events_sorted.mdm');
'20091217/prtrtc/beforemotionremoved/all_events_sorted_4_5_6_.mdm');



bv_write_combined_avg('/data1/MRI/Redrik',...
'20090930/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_1_2_3_.avg',...
'20091006/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_1_2_3_.avg');
'20091215/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');
'20091217/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_4_5_6_.avg');


%baseline LIP inactivation Redrik
bv_write_combined_mdm('/data1/MRI/Redrik',...
'20090928/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20091001/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20091004/prtrtc/beforemotionremoved/all_events_sorted.mdm');
'20091216/prtrtc/beforemotionremoved/all_events_sorted.mdm');
'20091221/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data1/MRI/Redrik',...
'20090928/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20091001/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20091004/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');
'20091216/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20091221/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



%--------------------------------------------------

%rPulv injection BASELINES
bv_write_combined_mdm('/data/MRI/Florian',...
'20090309/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090315/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090325/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090402/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090429/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090509/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data/MRI/Florian',...
'20090227/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090315/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090325/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090402/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090429/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090509/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

%------------

%area5
bv_write_combined_avg('/data/MRI/Florian',...
'20090306/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090313/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090404/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');


%area5
bv_write_combined_mdm('/data/MRI/Florian',...
'20090306/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090313/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090404/prtrtc/beforemotionremoved/all_events_sorted.mdm');

%write baselines area 5 
bv_write_combined_avg('/data/MRI/Florian',...
'20090315/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090325/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090402/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');


bv_write_combined_mdm('/data/MRI/Florian',...
'20090315/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090325/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090402/prtrtc/beforemotionremoved/all_events_sorted.mdm');

%-----



% rPulv injection INACTIVATION
bv_write_combined_mdm('/data/MRI/Florian',...
'20090311/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090317/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090323/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090507/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090513/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090515/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data/MRI/Florian',...
'20090311/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090317/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090323/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090507/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090513/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090515/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



bv_write_combined_mdm('/data/MRI/Florian',...
'20080821/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080822/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080823/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080824/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080825/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Florian',...
'20080821/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20080822/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20080823/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20080824/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20080825/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

% ---

bv_write_combined_mdm('/data/MRI/Florian',...
'20080819/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080820/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Florian',...
'20080819/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080820/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg');

bv_write_combined_avg('/data/MRI/Florian',...
'20090309/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090315/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



% Gutalin 09

bv_write_combined_mdm('/data/MRI/Gutalin',...
'20090206/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090208/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090210/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20090206/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090208/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090210/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



bv_write_combined_mdm('/data/MRI/Gutalin',...
'20090215/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090217/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20090215/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090217/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



bv_write_combined_mdm('/data/MRI/Gutalin',...
'20090105/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090106/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20090111/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20090105/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090106/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20090111/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');




% Redrik 4reward

bv_write_combined_mdm('/data1/MRI/Redrik',...
'20080320/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080321/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080325/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080326/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080327/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080328/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080401/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080402/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data1/MRI/Redrik',...
'20080320/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080321/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080325/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080326/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080327/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080328/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080401/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg',...
'20080402/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de_lrew__mem_r_2de_srew__mem_l_2de_lrew__mem_l_2de_srew__mem_r_lrew__mem_r_srew__mem_l_lrew__mem_l_srew.avg');







% ---

bv_write_combined_mdm('/data/MRI/Redrik',...
'20080804/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080805/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080806/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080807/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080811/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080814/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080815/prtrtc/beforemotionremoved/all_events_sorted.mdm',...     
'20080821/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20080824/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Redrik',...
'20080804/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080805/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080806/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080807/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080811/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080814/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080815/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...     
'20080821/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg',...
'20080824/prtrtc/aftermotionremoved/predsforvtc__mem_r__mem_l.avg');

% ---

bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg');

bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_vardir.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_vardir.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_vardir.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_vardir.avg');


bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_6_r__fix_dir_6_l__mem_6_r__mem_6_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg');

bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_10_r__fix_dir_10_l__mem_10_r__mem_10_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg');

bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_14_r__fix_dir_14_l__mem_14_r__mem_14_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg');

bv_write_combined_avg('D:\MRI\Human\MEMSAC-DIRSAC',...
'Kevin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Justin\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Aaron\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Chris\20060830\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Igor\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Helena\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Maricela\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg',...
'Michael\20070116\prtrtc\aftermotionremoved\predsforvtc__fix_dir_18_r__fix_dir_18_l__mem_18_r__mem_18_l_sorted_endper.avg');



bv_write_combined_mdm('/data/MRI/Redrik',...
'20070109/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070124/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070131/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070201/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070430/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070502/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070509/prtrtc/beforemotionremoved/all_events_sorted.mdm',...     
'20070515/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070516/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070618/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070622/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070627/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070628/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070703/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070823/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070829/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070831/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data/MRI/Gutalin',...
'20070705/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070706/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070709/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070710/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070711/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070713/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...        
'20070927/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070928/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071001/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071002/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071003/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071004/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071010/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071011/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071012/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

bv_write_combined_mdm('/data/MRI/Gutalin',...
'20070705/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070706/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070709/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070710/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070711/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070713/prtrtc/beforemotionremoved/all_events_sorted.mdm',...        
'20070927/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070928/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071001/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071002/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071003/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071004/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071010/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071011/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071012/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20070705/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070706/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070709/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070710/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20070711/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070713/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg');


bv_write_combined_avg('/data/MRI/Gutalin',...
'20070927/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070928/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071001/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071002/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20071003/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071004/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071010/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071011/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20071012/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20070927/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070928/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071001/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071002/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071003/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071004/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071010/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071011/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071012/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

bv_write_combined_mdm('/data/MRI/Gutalin',...
'20070927/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070928/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071001/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071002/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071003/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071004/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071010/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071011/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071012/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Redrik',...
'20070109/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070124/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070131/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070201/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...        
'20070430/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070502/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070509/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...   
'20070515/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070516/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070618/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070622/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070627/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070628/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070703/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070823/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070829/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070831/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071009/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



bv_write_combined_avg('/data/MRI/Redrik',...
'20070515/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070516/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070618/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070622/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20070627/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070628/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070703/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070823/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20070829/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070831/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20071009/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg');




% R bias
bv_write_combined_avg('/data/MRI/Redrik',...
'20070618/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070622/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070831/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071009/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

% L bias
bv_write_combined_avg('/data/MRI/Redrik',...
'20070515/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070516/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070627/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070628/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070703/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070823/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070829/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

bv_write_combined_avg('/data/MRI/Redrik',...
'20070515/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070516/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070618/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070622/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070627/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070628/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070703/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070823/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070829/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070831/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071009/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');


bv_write_combined_avg('/data/MRI/Gutalin',...
'20070927/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070928/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071001/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071002/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071003/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20071004/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');


bv_write_combined_mdm('/data/MRI/Gutalin',...
'20070927/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070928/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071001/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071002/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071003/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20071004/prtrtc/beforemotionremoved/all_events_sorted.mdm');



bv_write_combined_avg('/data/MRI/Redrik',...
'20070515/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070516/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070618/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070622/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070627/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070628/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070703/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070823/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070829/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070831/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');



bv_write_combined_mdm('/data/MRI/Redrik',...
'20070515/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070516/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070618/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070622/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070627/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070628/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070703/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070823/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070829/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070831/prtrtc/beforemotionremoved/all_events_sorted.mdm');



bv_write_combined_mdm('/data/MRI/Gutalin',...
'20070705/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070706/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070709/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070710/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070711/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070713/prtrtc/beforemotionremoved/all_events_sorted.mdm');


bv_write_combined_avg('/data/MRI/Gutalin',...
'20070705/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070706/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070709/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070710/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070711/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg',...
'20070713/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l.avg');

 



bv_write_combined_avg('/data/MRI/Redrik',...
'20070109/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070124/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070131/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070201/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...        
'20070430/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070502/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg',...
'20070509/prtrtc/aftermotionremoved/predsforvtc__sac_mem2de_r_sl__sac_mem2de_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_mem2de_r_ll__sac_mem2de_l_ll__sac_mem_r_ll__sac_mem_l_ll_sac.avg');







bv_write_combined_avg('/data/MRI/Redrik',...
'20070109/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070124/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070131/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070201/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...        
'20070430/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070502/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070509/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg');





bv_write_combined_avg('/data/MRI/Redrik',...
'20070430/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070502/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070509/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070510/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg');


bv_write_combined_mdm('/data/MRI/Redrik',...
'20070430/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070502/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070509/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070510/prtrtc/beforemotionremoved/all_events_sorted.mdm');







bv_write_combined_avg('/data/MRI/Gutalin',...
'20051026/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
'20051030/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
'20051102/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');


bv_write_combined_mdm('/data/MRI/Redrik',...
'20070316/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070322/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Redrik',...
'20070316/prtrtc/aftermotionremoved/all_runs.avg',...
'20070316/prtrtc/aftermotionremoved/all_runs.avg');


bv_write_combined_mdm('/data/MRI/Redrik',...
'20070109/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
'20070124/prtrtc/beforemotionremoved/all_events_sorted.mdm');

bv_write_combined_avg('/data/MRI/Redrik',...
'20070109/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070124/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070131/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070201/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070216/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070218/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg');

% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20061215/prtrtc/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__mem_r__mem_l_sorted.avg',...
% '20061229/prtrtc/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__mem_r__mem_l_sorted.avg');

bv_write_combined_avg('/data/MRI/Gutalin',...
'20070112/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg',...
'20070117/prtrtc/aftermotionremoved/predsforvtc__mem_r_2de__mem_l_2de__mem_r__mem_l_sorted.avg');

% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20051026/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051030/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051102/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060317/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060323/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060329/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060404/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060405/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg');


% bv_write_combined_avg('/data/MRI/Redrik',...
% '20051024/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051025/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051027/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051028/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051101/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051201/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051207/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20051209/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060316/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060321/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060322/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060509/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060526/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',....
% '20060531/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060509/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',...
% '20060526/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg',....
% '20060531/prtrtc/aftermotionremoved/predsforvtc__sac_dir_r_sl__sac_dir_l_sl__sac_mem_r_sl__sac_mem_l_sl__sac_dir_r_ll__sac_dir_l_ll__sac_mem_r_ll__sac_mem_l_ll_sorted.avg');




% bv_write_combined_mdm('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060612/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060623/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060629/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060803/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060807/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060808/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060809/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm');
% 
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060612/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060623/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060629/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');
% 
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060612/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060623/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060629/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060612/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060623/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060629/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg');
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...   
% '20060612/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...   
% '20060623/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...   
% '20060629/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg');
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060608/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060612/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060623/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060629/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_r__fix_dir_l__fix_dir_t__fix_dir_b__mem_r__mem_l__mem_t__mem_b_sorted.avg');





% 
% bv_write_combined_mdm('/data/MRI/Redrik',...
% '20060509/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
% '20060526/prtrtc/beforemotionremoved/all_events_sorted.mdm',...
% '20060531/prtrtc/beforemotionremoved/all_events_sorted.mdm');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060509/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060526/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060531/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060509/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060526/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060531/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060526/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060531/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');
% 
% 
% bv_write_combined_mdm('/data/MRI/Gutalin',...
% '20060920/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060926/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060927/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm');
% 
% 
% bv_write_combined_mdm('/data/MRI/Gutalin',...
% '20060920/prtrtc_supprc/beforemotionremoved/all_events_sorted.mdm',...
% '20060926/prtrtc_supprc/beforemotionremoved/all_events_sorted.mdm',...
% '20060927/prtrtc_supprc/beforemotionremoved/all_events_sorted.mdm');
% 
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060920/prtrtc_special_timing/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060926/prtrtc_special_timing/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060927/prtrtc_special_timing/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060928/prtrtc_special_timing/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg');
% 
% 
% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060920/prtrtc_supprc/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060926/prtrtc_supprc/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060927/prtrtc_supprc/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg',...
% '20060928/prtrtc_supprc/aftermotionremoved/predsforvtc__mem_r__mem_l_sorted.avg');



% bv_write_combined_mdm('/data/MRI/Gutalin',...
% '20060727/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060731/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060801/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060803/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060807/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060808/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060809/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm');


% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20060727/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060731/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060801/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...   
% '20060803/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');


% 
% bv_write_combined_mdm('/data/MRI/Redrik',...
% '20060809/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060808/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060807/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060805/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060804/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm',...
% '20060802/prtrtc_special_timing/beforemotionremoved/all_events_sorted.mdm');


% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060802/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...       
% '20060804/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...    
% '20060805/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',... 
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',... 
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060802/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...   
% '20060804/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...   
% '20060805/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...  
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...   
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');
% 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060802/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...    
% '20060804/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060805/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...    
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...    
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6__fix_dir_8__fix_dir_10__fix_dir_12__mem_6__mem_8__mem_10__mem_12_sorted_vardir.avg');
% % 
% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060802/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060804/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060805/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060807/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...   
% '20060808/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg',...
% '20060809/prtrtc_special_timing/aftermotionremoved/predsforvtc__fix_dir_6_r__fix_dir_8_r__fix_dir_10_r__fix_dir_12_r__mem_6_r__mem_8_r__mem_10_r__mem_12_r__fix_dir_6_l__fix_dir_8_l__fix_dir_10_l__fix_dir_12_l__mem_6_l__mem_8_l__mem_10_l__mem_12_l_sorted_vardir.avg');

% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20051026/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051030/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051102/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...   
% '20060317/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060323/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060329/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060404/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060405/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');


% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20051026/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051030/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051102/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...   
% '20060317/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060323/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060329/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060404/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060405/prtrtc8/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');



% bv_write_combined_avg('/data/MRI/Gutalin',...
% '20051026/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20051030/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20051102/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...   
% '20060317/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060323/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060329/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060404/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg',...
% '20060405/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_notsorted.avg');



% bv_write_combined_avg('/data/MRI/Redrik',...
% '20051024/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051025/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051027/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051028/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051101/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');


% bv_write_combined_avg('/data/MRI/Redrik',...
% '20051201/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051207/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051209/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060118/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060119/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');



% bv_write_combined_avg('/data/MRI/Redrik',...
% '20060316/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060321/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060322/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');


% '20060118/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060119/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...


% bv_write_combined_avg('/data/MRI/Redrik',...
% '20051024/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051025/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051027/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051028/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051101/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051201/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051207/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20051209/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060316/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060321/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
% '20060322/prtrtc/aftermotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');

bv_write_combined_avg('/data/MRI/Redrik',...
'20051024/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051025/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051027/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051028/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051101/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051201/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051207/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20051209/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20060316/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20060321/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg',...
'20060322/prtrtc/beforemotionremoved/predsforvtc__fix_dir_cor__mem_cor_sorted.avg');



